### ISSUE TITLE
Functional children and React.Component cause rerenders

### ISSUE THREAD

**Issue by jknight12882** [opencomponents/react-oc#1]
Even though `OpenComponent` only relies on a few `this.props`, it will always rerender, even though the props never change. 

https://github.com/opencomponents/react-oc/blob/d87fab61cf3c9d04d035f543060fe0de646196b4/packages/react-oc/src/OpenComponent.js#L15

Also, since it is passing an anonymous function as the `children` prop, that will force `OpenComponentsContext` to rerender every time. 

https://github.com/opencomponents/react-oc/blob/d87fab61cf3c9d04d035f543060fe0de646196b4/packages/react-oc/src/OpenComponent.js#L20

Consider using `PureComponents` and bound functions to prevent unnecessary rerenders

**Comment by dipunm** [comment]
Thanks for creating this issue.

I would like to understand the problem a little more. For the first issue, are you suggesting that doing something like below would re-render if props.unused changed?
```jsx
(props) => (
    <OpenComponent name="my-component" otherUnusedProp={props.unused} />
)
```

Or is this more sinister such that even below may re-render even though props didn't change?
```jsx
(props) => (
    <OpenComponent name="my-component" />
)
```

Re: the suggestion of using a PureComponent, one thing we may need to keep in mind, is that parameters is an object type so PureComponent may not be the most appropriate solution.

For the second issue, I do not really understand why using an anonymous function would cause a re-render of the OpenComponentsContext. The documentation on the React website ([link](https://reactjs.org/docs/context.html#contextconsumer)) also uses an anonymous function in their example.

It may be helpful to create a demo application that highlights these issues. This repository has a demo application that hosts its own local open-components registry which allows us to demo/test functionality publicly without exposing details of our private registries. Creating a fork and adding console logs / extra functionality to show off the bug will be very helpful.

**Comment by dipunm** [comment]
Closing for now due to a lack of any sort of response. Please feel free to contact me directly if you'd like to continue this conversation and we can re open this issue.

Thanks.
